name: 'Snapcraft Review Tools'
description: 'Review your built Snap package using the same tools as the Snap Store'
author: 'Daniel Llewellyn'
inputs:
  snap:
    description: 'The snap file to upload to the store'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
