name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  unit: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install
        npm run all

  integration-snapcore: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: snapcore/action-build@v1
      id: build
      with:
        path: './sample-project'
    - run: |
        sudo chgrp runner ${{ steps.build.outputs.snap }}
        snap version
        snap list
        ls -ld /tmp
        ls -l ${{ steps.build.outputs.snap }}
        lsattr ${{ steps.build.outputs.snap }}
    - uses: ./
      with:
        snap: ${{ steps.build.outputs.snap }}

  integration-multiarch: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: diddlesnaps/snapcraft-multiarch-action@v1
      id: build
      with:
        path: './sample-project'
    - run: |
        sudo groupadd --force --system lxd
        sudo usermod --append --groups lxd runner
        sudo snap refresh lxd
        sudo lxd init --auto
        sudo iptables -P FORWARD ACCEPT
        sudo snap install --channel stable --classic snapcraft
        sudo chgrp runner ${{ steps.build.outputs.snap }}
        snap version
        snap list
        ls -ld /tmp
        ls -l ${{ steps.build.outputs.snap }}
        lsattr ${{ steps.build.outputs.snap }}
    - uses: ./
      with:
        snap: sample-project/test-diddledani-review-action_0.1_amd64.snap
