name: test-diddledan-review-action
base: core18
version: '0.1'
summary: A snap used to test the Github review action
description: |
  This is a trivial snap used to test that the Github review action
  can successfully review snaps.
grade: stable
confinement: strict

apps:
  test-diddledan-review-action:
    command: hello.sh

parts:
  build:
    # See 'snapcraft plugins'
    plugin: dump
    source: bin
    stage:
      - hello.sh